version: '3.6'
services:
 api:
   container_name: api
   build:
     context: ./
     dockerfile: Dockerfile
   volumes:
     - ./:/root/src
   healthcheck:
     disable: true
   restart: unless-stopped
   ports:
     - 8080:8080
   tty: true
 db:
   image: mongo:latest
   ports:
     - 8080:8080
   environment:
     MONGO_INITDB_ROOT_USERNAME: nombreusuario
     MONGO_INITDB_ROOT_PASSWORD: contraseñaDB
     MONGO_INITDB_DATABASE: nombreDB